name = "copyright-vault"
main = "worker/index.ts"
compatibility_date = "2026-07-15"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "viral-drm-db"
database_id = "b77c56d1-6344-431b-bca2-bf34cdb5d5ca"
migrations_dir = "migrations"
